roe_by_industry = {
    "Advertising Agencies": -5.6,
    "Aerospace & Defense": 5.8,
    "Agricultural Inputs": 4.2,
    "Airlines": 6.6,
    "Apparel Manufacturing": 5.7,
    "Apparel Retail": 17.9,
    "Asset Management": 9.2,
    "Auto Manufacturers": -2.5,
    "Auto Parts": 3.1,
    "Auto & Truck Dealerships": 7.4,
    "Banks - Diversified": 12.9,
    "Banks - Regional": 7.7,
    "Beverages - Non-Alcoholic": 32.2,
    "Beverages - Wineries & Distilleries": 9,
    "Biotechnology": -64.4,
    "Broadcasting": -11.2,
    "Building Materials": 18.4,
    "Building Products & Equipment": 18.2,
    "Business Equipment & Supplies": 8.3,
    "Capital Markets": 11.8,
    "Chemicals": 5.7,
    "Communication Equipment": -6.7,
    "Computer Hardware": -13.5,
    "Conglomerates": -1.6,
    "Consulting Services": 12.3,
    "Consumer Electronics": -17,
    "Credit Services": 8.7,
    "Department Stores": 17.7,
    "Diagnostics & Research": -26.2,
    "Discount Stores": 19,
    "Drug Manufacturers - General": 26.1,
    "Drug Manufacturers - Specialty & Generic": -38.8,
    "Education & Training Services": 10.5,
    "Electrical Equipment & Parts": 7.2,
    "Electronic Components": 1.4,
    "Electronic Gaming & Multimedia": -10.9,
    "Electronics & Computer Distribution": 11.1,
    "Engineering & Construction": 12.9,
    "Entertainment": -11.2,
    "Farm & Heavy Construction Machinery": 11.1,
    "Farm Products": 8.4,
    "Financial Data & Stock Exchanges": 13,
    "Food Distribution": 5.6,
    "Footwear & Accessories": 16,
    "Furnishings, Fixtures & Appliances": 10.6,
    "Gambling": 12.5,
    "Gold": 0.8,
    "Grocery Stores": 15.9,
    "Healthcare Plans": -19.4,
    "Health Information Services": -29.5,
    "Home Improvement Retail": 2.6,
    "Household & Personal Products": 10.3,
    "Industrial Distribution": 12.8,
    "Information Technology Services": 7.6,
    "Insurance Brokers": 5.3,
    "Insurance - Diversified": 13,
    "Insurance - Life": 10.5,
    "Insurance - Property & Casualty": 13.6,
    "Insurance - Reinsurance": 15.6,
    "Insurance - Specialty": 10.5,
    "Integrated Freight & Logistics": 12.1,
    "Internet Content & Information": -2.9,
    "Internet Retail": 5.3,
    "Leisure": 5.3,
    "Luxury Goods": 2.4,
    "Marine Shipping": 15.4,
    "Medical Care Facilities": -11.2,
    "Medical Devices": -37.9,
    "Medical Distribution": 8.2,
    "Medical Instruments & Supplies": -28,
    "Metal Fabrication": 12.9,
    "Mortgage Finance": 6.6,
    "Oil & Gas Drilling": 2.6,
    "Oil & Gas E&P": 14.9,
    "Oil & Gas Equipment & Services": 9.1,
    "Oil & Gas Integrated": 7.6,
    "Oil & Gas Midstream": 17.5,
    "Oil & Gas Refining & Marketing": 8.1,
    "Other Industrial Metals & Mining": -12.8,
    "Other Precious Metals & Mining": -0.9,
    "Packaged Foods": 8.8,
    "Packaging & Containers": 15.3,
    "Paper & Paper Products": -3.9,
    "Personal Services": 18.3,
    "Pharmaceutical Retailers": -43.5,
    "Pollution & Treatment Controls": 13.6,
    "Publishing": 2.4,
    "Railroads": 22.3,
    "Real Estate - Development": 2.5,
    "Real Estate - Diversified": 6.8,
    "Real Estate Services": 3,
    "Recreational Vehicles": 3,
    "REIT - Diversified": 4.3,
    "REIT - Healthcare Facilities": 2,
    "REIT - Hotel & Motel": 2.4,
    "REIT - Industrial": 4.9,
    "REIT - Mortgage": 3.1,
    "REIT - Office": -0.8,
    "REIT - Residential": 3.3,
    "REIT - Retail": 6.5,
    "REIT - Specialty": 9,
    "Rental & Leasing Services": 14.1,
    "Residential Construction": 19.4,
    "Resorts & Casinos": 11.2,
    "Restaurants": 12.3,
    "Scientific & Technical Instruments": 6.2,
    "Security & Protection Services": 17.4,
    "Semiconductor Equipment & Materials": 8,
    "Semiconductors": 1.1,
    "Software - Application": -5.9,
    "Software - Infrastructure": 0.8,
    "Solar": -8.4,
    "Specialty Business Services": 11.8,
    "Specialty Chemicals": 8.4,
    "Specialty Industrial Machinery": 11.6,
    "Specialty Retail": 12.2,
    "Staffing & Employment Services": 7.6,
    "Steel": 3.5,
    "Telecom Services": -1.8,
    "Thermal Coal": 15.8,
    "Tools & Accessories": 11.4,
    "Travel Services": 19.3,
    "Trucking": 6.1,
    "Utilities - Diversified": 9.4,
    "Utilities - Regulated Electric": 9.5,
    "Utilities - Regulated Gas": 9.9,
    "Utilities - Regulated Water": 10.1,
    "Utilities - Renewable": 5.1,
    "Waste Management": 6.5
}
